import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { loadConfig, ConfigError } from '../src/config.js';
import { HttpError, type PrintApi } from '../src/http-client.js';
import { JobLedger } from '../src/ledger.js';
import { ConsoleLogger, type Logger } from '../src/logger.js';
import { parsePrintJob, payloadHash, JobValidationError } from '../src/model.js';
import { MockPrinter, PrinterError } from '../src/printer.js';
import { renderKitchenTicket } from '../src/renderer.js';
import type { AgentConfig, PrintJob } from '../src/types.js';
import { PrintWorker } from '../src/worker.js';

const dir = () => mkdtempSync(join(tmpdir(), 'pinta-agent-'));
const config = (dataDir = dir()): AgentConfig => ({ serverUrl: 'https://example.test', agentToken: 'top-secret-token', locationId: 'pinta-main', dataDir, longPollWaitSeconds: 25, requestTimeoutMs: 40000, printer: { driver: 'mock' } });
const rawJob = (claim = 'A', changes: Record<string, unknown> = {}) => ({ schema_version: 1, job_id: 'job-1', claim_token: claim, lease_expires_at: '2026-09-03T12:00:00Z', order: { number: 146, time: '22:11', items: [{ quantity: 1, name: 'Burger Pinta', variant: 'Simple', removed_ingredients: ['cebolla'], added_extras: ['medallón extra'], sauces: ['mayonesa', 'ketchup'] }], summary: { total_medallions: 13, cheese_counts: { cheddar: 5, mozzarella: 3, roquefort: 2, provolone: 1 }, no_cheese_count: 2 }, customer_phone: 'DO NOT PRINT', address: 'DO NOT PRINT', total: 9999, payment: 'cash' }, ...changes });
const job = (claim = 'A', changes: Record<string, unknown> = {}) => parsePrintJob(rawJob(claim, changes));
class MemoryLogger implements Logger { events: string[] = []; info(e: string) { this.events.push(e); } warn(e: string) { this.events.push(e); } error(e: string) { this.events.push(e); } }
class FakeBackend implements PrintApi { acks: Array<{ claim: string; result: string }> = []; failed: string[] = []; ackError: Error | undefined; jobs: Array<PrintJob | undefined> = []; aborted = false; async health() {} async nextJob() { return this.jobs.shift(); } async ackPrinted(x: PrintJob) { this.acks.push({ claim: x.claim_token, result: 'printed' }); if (this.ackError) throw this.ackError; } async ackFailed(x: PrintJob) { this.failed.push(x.claim_token); } abort() { this.aborted = true; } close() {} }
const worker = (ledger: JobLedger, printer: MockPrinter, api = new FakeBackend(), logger = new MemoryLogger()) => new PrintWorker(config(), api, printer, ledger, logger, async () => {}, () => 0);

test('config loads and rejects a missing token', () => { const path = join(dir(), 'config.json'); writeFileSync(path, JSON.stringify({ server_url: 'https://pinta.test/', agent_token: 'x', printer: { driver: 'mock' } })); assert.equal(loadConfig(path).serverUrl, 'https://pinta.test'); writeFileSync(path, JSON.stringify({ server_url: 'https://pinta.test', agent_token: '', printer: { driver: 'mock' } })); assert.throws(() => loadConfig(path), ConfigError); });
test('logger never includes tokens', () => { const output: string[] = []; const old = console.log; console.log = (x: string) => output.push(x); try { new ConsoleLogger().info('startup', { agent_token: 'top-secret-token', server_host: 'x' }); } finally { console.log = old; } assert.equal(output.join('').includes('top-secret-token'), false); });
test('renderer dynamically includes cheeses and excludes private/payment fields', () => { const ticket = renderKitchenTicket(job()).text; for (const line of ['CHEDDAR: 5', 'MOZZARELLA: 3', 'ROQUEFORT: 2', 'PROVOLONE: 1', 'SIN QUESO: 2']) assert.match(ticket, new RegExp(line)); for (const forbidden of ['DO NOT PRINT', '9999', 'CASH']) assert.equal(ticket.includes(forbidden), false); });
test('new job prints, persists before ACK, then ACKs', async () => { const path = join(dir(), 'agent.sqlite'); const ledger = new JobLedger(path); const printer = new MockPrinter(); const api = new FakeBackend(); await worker(ledger, printer, api).processJob(job()); assert.equal(printer.calls, 1); assert.equal(ledger.get('job-1')?.status, 'ACKED'); assert.deepEqual(api.acks, [{ claim: 'A', result: 'printed' }]); ledger.close(); });
test('lost ACK then reclaim does not print twice and uses new claim', async () => { const path = join(dir(), 'agent.sqlite'); const ledger = new JobLedger(path); const printer = new MockPrinter(); const api = new FakeBackend(); api.ackError = new HttpError('TEMPORARY', 'timeout'); const w = worker(ledger, printer, api); await w.processJob(job('A')); assert.equal(ledger.get('job-1')?.status, 'PRINTED'); assert.equal(printer.calls, 1); api.ackError = undefined; await w.processJob(job('B')); assert.equal(printer.calls, 1); assert.equal(ledger.get('job-1')?.status, 'ACKED'); assert.deepEqual(api.acks.map((x) => x.claim), ['A', 'B']); ledger.close(); });
test('restart with the same SQLite remembers PRINTED and ACKs claim B', async () => { const path = join(dir(), 'agent.sqlite'); const first = new JobLedger(path); const p1 = new MockPrinter(); const api1 = new FakeBackend(); api1.ackError = new HttpError('TEMPORARY', 'timeout'); await worker(first, p1, api1).processJob(job('A')); first.close(); const second = new JobLedger(path); const p2 = new MockPrinter(); const api2 = new FakeBackend(); await worker(second, p2, api2).processJob(job('B')); assert.equal(p1.calls + p2.calls, 1); assert.equal(second.get('job-1')?.status, 'ACKED'); second.close(); });
test('stale claim 409 retains PRINTED and a printer failure is FAILED then retryable', async () => { const path = join(dir(), 'agent.sqlite'); const ledger = new JobLedger(path); const printer = new MockPrinter(); const api = new FakeBackend(); api.ackError = new HttpError('CONFLICT', 'stale'); await worker(ledger, printer, api).processJob(job()); assert.equal(ledger.get('job-1')?.status, 'PRINTED'); ledger.close(); const path2 = join(dir(), 'agent.sqlite'); const failedLedger = new JobLedger(path2); const failedApi = new FakeBackend(); await worker(failedLedger, new MockPrinter({ failure: new PrinterError('offline', 'PRINTER_OFFLINE') }), failedApi).processJob(job('A')); assert.equal(failedLedger.get('job-1')?.status, 'FAILED'); await worker(failedLedger, new MockPrinter(), failedApi).processJob(job('B')); assert.equal(failedLedger.get('job-1')?.status, 'ACKED'); failedLedger.close(); });
test('abandoned PRINTING becomes AMBIGUOUS and is never silently reprinted', async () => { const path = join(dir(), 'agent.sqlite'); const ledger = new JobLedger(path); ledger.receive(job()); ledger.setPrinting(job()); ledger.close(); const reopened = new JobLedger(path); assert.equal(reopened.markAbandonedPrintingAmbiguous(), 1); const printer = new MockPrinter(); const result = await worker(reopened, printer).processJob(job('B')); assert.equal(result, 'AMBIGUOUS'); assert.equal(printer.calls, 0); reopened.close(); });
test('payload mismatch, unsupported schema, and bad medallion summary are rejected', () => { const a = job(); const changed = job('B', { order: { ...rawJob().order, number: 147 } }); assert.notEqual(payloadHash(a), payloadHash(changed)); assert.throws(() => parsePrintJob({ ...rawJob(), schema_version: 2 }), (e: unknown) => e instanceof JobValidationError && e.code === 'UNSUPPORTED_SCHEMA_VERSION'); assert.throws(() => parsePrintJob({ ...rawJob(), order: { ...rawJob().order, summary: { ...rawJob().order.summary, total_medallions: 1 } } }), /total_medallions/); });
test('mock printer delay, counter, and unique output files work', async () => { const output = dir(); const printer = new MockPrinter({ dataDir: output, delayMs: 2 }); const ticket = renderKitchenTicket(job()); await printer.print(ticket, 'job-x'); await printer.print(ticket, 'job-x'); assert.equal(printer.calls, 2); assert.match(readFileSync(join(output, 'mock-output', '146_job-x.txt'), 'utf8'), /PEDIDO #146/); });
