from enum import Enum
class AgentState(str,Enum):
    STARTING="STARTING"; RUNNING="RUNNING"; IDLE="IDLE"; PRINTING="PRINTING"; ACKING="ACKING"; AUTH_ERROR="AUTH_ERROR"; SERVER_ERROR="SERVER_ERROR"; PRINTER_ERROR="PRINTER_ERROR"; PROTOCOL_ERROR="PROTOCOL_ERROR"; STOPPING="STOPPING"; STOPPED="STOPPED"; ERROR="ERROR"
class ServerState(str,Enum): UNKNOWN="UNKNOWN"; CONNECTING="CONNECTING"; CONNECTED="CONNECTED"; DISCONNECTED="DISCONNECTED"; AUTH_ERROR="AUTH_ERROR"; PROTOCOL_ERROR="PROTOCOL_ERROR"

