import { join } from 'node:path';
import { loadConfig } from './config.js';
import { HttpPrintApi } from './http-client.js';
import { JobLedger } from './ledger.js';
import { ConsoleLogger } from './logger.js';
import { createPrinterRuntime } from './printer-factory.js';
import { PrintWorker } from './worker.js';
const config = loadConfig(); const logger = new ConsoleLogger(); const api = new HttpPrintApi(config); const ledger = new JobLedger(join(config.dataDir, 'agent.sqlite')); const runtime = createPrinterRuntime(config); const worker = new PrintWorker(config, api, runtime.printer, ledger, logger, { renderTicket: runtime.renderTicket });
process.once('SIGINT', () => worker.stop()); process.once('SIGTERM', () => worker.stop());
await worker.run();
